name: .NET_Auto_Tests

# this trigger which run our actions when we did commit or create pull request for master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # name action
  RunTests:
    # we are using ubuntu for autoruning
    runs-on: ubuntu-latest

    # our action
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
